### PR TITLE
Wednesday Homework

### PR DESCRIPTION
**Pull request by Manderson3568**
_If you had no problems you can just leave it empty_

- How difficult did you find this (out of 10)? (0 being no problems at all, 10 being impossible)
- 6
- Was there anything that you struggled with?
- while loops and index functions caused some weird interactions 
- Is there any particular code you want me to look into?
- Is there anything that you'd like some further information on?
- Roughly how long did it take?
- 3 hours

### CODE REVIEW

**Comment by Tenzang** [comment]
> Was there anything that you struggled with?
while loops and index functions caused some weird interactions

Whats an index function? o.O

**Comment by Manderson3568** [comment]
sorry indexOf() was feeding into the stop parameter or the while loop, but I ended up with a couple of infinite loops because I was either finding the same indexOf() result infinitely or added 1 to find the next character, but caused me to loop infinitely because the -1 became a 0 before the while loop evaluated it.

**Comment by Manderson3568** [comment]
lines 30-50 in the code

**Comment by Tenzang** [comment]
I see! Glad you cracked that.

**Pull request merged**
